# Generated by Buildr 1.4.7, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "jnomics-client"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

COMMONS_CLI = 'commons-cli:commons-cli:jar:1.2'
THRIFT = 'org.apache.thrift:libthrift:jar:0.8.0'
HADOOP_CORE = 'org.apache.hadoop:hadoop-core:jar:1.1.0'

desc "The Jnomics-client project"
define "jnomics-client" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  compile.with COMMONS_CLI, THRIFT, HADOOP_CORE
  package(:jar)

end
